### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for SeqLabel:

### ISSUE THREAD

**Issue by Biaocsu** [jiesutd/NCRFpp#120]
你好，在使用decode模式时，我想预测一个文件夹下所有文件而不是指定的一个文件，这样的场景对我更合适。但是预测到第二个文件就会出错，请问该怎样解决呢？谢谢
Traceback (most recent call last):
  File "main.py", line 567, in <module>
    decode_results, pred_scores = load_model_decode(data, 'raw')
  File "main.py", line 491, in load_model_decode
    model.load_state_dict(torch.load(data.load_model_dir))
  File "C:\install\anaconda\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SeqLabel:
        size mismatch for word_hidden.hidden2tag.weight: copying a param with shape torch.Size([17, 200]) from checkpoint, the shape in current model is torch.Size([19, 200]).
        size mismatch for word_hidden.hidden2tag.bias: copying a param with shape torch.Size([17]) from checkpoint, the shape in current model is torch.Size([19]).
        size mismatch for crf.transitions: copying a param with shape torch.Size([17, 17]) from checkpoint, the shape in current model is torch.Size([19, 19]).

**Comment by Biaocsu** [comment]
我试过每预测一个文件，在循环中每次都加载模型，即把
data.load(data.dset_dir)
data.read_config(args.config)
放在循环里面不会报错，但这样效率太低，因为会多次加载模型。
将模型文件放在循环外面，只加载一次才会出现上述问题

**Comment by Biaocsu** [comment]
I already solved this problem, so I will close it
