### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by HongyanJiao** [jiesutd/NCRFpp#121]
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 445, in <module>
    train(data)
  File "main.py", line 357, in train
    loss.backward()
  File "/home/jhy/py2.7/local/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jhy/py2.7/local/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by jiesutd** [comment]
cuda out of memory
